//Временная аутентификация
export const CHANGE_LOGIN = 'CHANGE_LOGIN'
//Инпуты формы homepage
export const CHANGE_TEXT_LOGIN_HOMEPAGE = 'CHANGE_TEXT_HOMEPAGE'
export const CHANGE_TEXT_PASS_HOMEPAGE = 'CHANGE_PASS_HOMEPAGE'
//Валидация
export const VALIDATION_LOGIN_ACTIVE = 'VALIDATION_LOGIN_ACTIVE'
export const VALIDATION_PASS_ACTIVE = 'VALIDATION_PASS_ACTIVE'
//Ошибки
export const VALIDATION_LOGIN_ERROR = 'VALIDATION_LOGIN_ERROR'
export const VALIDATION_PASS_ERROR = 'VALIDATION_PASS_ERROR'
